FROM ubuntu:latest

COPY . /app
WORKDIR /app
RUN apt-get update -y
RUN apt-get install -y python3-pip python3-dev build-essential
RUN pip3 install -r requirements.txt
EXPOSE 5000
CMD ["/usr/bin/gunicorn", "--config", "/gunicorn_config.py", "app"]

