FROM tiangolo/uwsgi-nginx-flask:python3.6

RUN rm /app/prestart.sh


COPY requirements.txt /tmp/
RUN pip install -U pip
RUN pip install -r /tmp/requirements.txt

COPY ./app.py /app/main.py
COPY ./resources /app/resources
COPY ./resources_g3 /app/resources_g3
